### ISSUE TITLE
Broccoli plugin fails to build with a fresh new application

### ISSUE THREAD

**Issue by fr0gs** [glimmerjs/glimmer-application-pipeline#125]
``
> my-app@0.0.0 start /home/esteban/gits/test/my-app
> ember server

Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49153
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Project.require (/home/esteban/gits/test/my-app/node_modules/ember-cli/lib/models/project.js:322:14)
    at Project.targets (/home/esteban/gits/test/my-app/node_modules/ember-cli/lib/models/project.js:238:28)
    at RollupWithDependencies.build (/home/esteban/gits/test/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/rollup-with-dependencies.js:64:38)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/home/esteban/gits/test/my-app/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/esteban/gits/test/my-app/node_modules/broccoli-merge-trees/index.js:16:10)
    at GlimmerApp.package (/home/esteban/gits/test/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:256:23)
    at GlimmerApp.toTree (/home/esteban/gits/test/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:287:28)
    at module.exports (/home/esteban/gits/test/my-app/ember-cli-build.js:10:14)
    at Builder.setupBroccoliBuilder (/home/esteban/gits/test/my-app/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/esteban/gits/test/my-app/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/home/esteban/gits/test/my-app/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at /home/esteban/gits/test/my-app/node_modules/ember-cli/lib/models/command.js:243:46
    at tryCatch (/home/esteban/gits/test/my-app/node_modules/rsvp/dist/rsvp.js:525:12)

```

My ember-cli, npm and nodejs versions are:

```sh
my-app:master* λ npm -v
5.3.0
my-app:master* λ ember -v
ember-cli: 2.14.1
node: 4.8.4
os: linux x64
```

This can be fixed just by adding `'use strict';` on top of **config/targets.js**

**Comment by rwjblue** [comment]
Would love a PR adding the required use strict line, you would fix it over in glimmerjs/glimmer-blueprint.

**Comment by fr0gs** [comment]
You got it https://github.com/glimmerjs/glimmer-blueprint/pull/60/files
