### ISSUE TITLE
Modules without default break things

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-application-pipeline#4]
Doesn't seem to allow a module that doesn't provide a `default` export. Workaround is to just add `export default {};`.

Repro `hello-world` branch: https://github.com/asakusuma/hello-glimmer/tree/ts-bug

```
The Broccoli Plugin: [RollupWithDependencies] failed with:
Error: 'default' is not exported by tmp/rollup_with_dependencies-input_base_path-AIKLAY2D.tmp/ui/components/hello-world/foo.js
    at error (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:7997:2)
    at Module.trace (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:8095:9)
    at ModuleScope.findDeclaration (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:7681:22)
    at Identifier.bind (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:6733:29)
    at /Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:5291:50
    at Node.eachChild (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:5308:5)
    at Node.bind (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:5291:7)
    at /Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:5291:50
    at ObjectExpression.eachChild (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/node_modules/rollup/dist/rollup.js:5305:19)

The broccoli plugin was instantiated at: 
    at RollupWithDependencies.Plugin (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-plugin/index.js:7:31)
    at RollupWithDependencies.Rollup (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/broccoli-rollup/dist/index.js:51:72)
    at new RollupWithDependencies (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/@glimmer/application-pipeline/lib/broccoli/rollup-with-dependencies.js:19:10)
    at GlimmerApp.toTree (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/@glimmer/application-pipeline/lib/broccoli/glimmer-app.js:157:12)
    at module.exports (/Users/akusuma/workspace/opensource/hello-glimmer/ember-cli-build.js:23:14)
    at CoreObject.setupBroccoliBuilder (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/ember-cli/lib/models/builder.js:72:19)
    at CoreObject.init (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/ember-cli/lib/models/builder.js:52:10)
    at CoreObject.superWrapper [as init] (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/core-object/core-object.js:32:33)
    at CoreObject.run (/Users/akusuma/workspace/opensource/hello-glimmer/node_modules/ember-cli/lib/tasks/serve.js:15:19)
```

**Comment by robbiepitts** [comment]
Problem is ResolutionMapBuilder is trying to build into the module map _every_ file, except for those in config:

```js
var resolvableTree = find([appTree, hbsTree], {
  srcDir: 'src',
  include: ['**/*.js', '**/*.hbs'],
  exclude: ['config/**']
});
```

Then Rollup blows up when it hits the invalid imports in `module-map.js`.

We either need to make this funnel more selective or make ResolutionMapBuilder more selective. Or perhaps part of the module unification structure is not having any files or directories that deviate?

**Comment by ksnyde** [comment]
I'm having something that appears related to this issue. In my case the Typescript library I'm importing does _not_ have a default export but exports a class on a single named export. I'd like to understand a bit better what is actually failing here ... can anyone point me to some resources? 

As for the work-around ... how does one export a default export as suggested above from a 3rd party library which already has typings? Do I need to declare my own namespace and override the interface definition?

**Comment by ksnyde** [comment]
ok, got my problem sorted ... https://github.com/glimmerjs/glimmer-application-pipeline#importing-commonjs-modules
