### ISSUE TITLE
Error when starting a new app

### ISSUE THREAD

**Issue by batusai513** [glimmerjs/glimmer-application-pipeline#99]
Hi, when i try to run a new app generated with ember-cli i get this
```
Class constructor AbstractBuild cannot be invoked without 'new'
TypeError: Class constructor AbstractBuild cannot be invoked without 'new'
    at new GlimmerApp (/home/richard/projects/glimmer-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:111:24)
    at module.exports (/home/richard/projects/glimmer-app/ember-cli-build.js:6:13)
    at Builder.setupBroccoliBuilder (/home/richard/projects/glimmer-app/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/richard/projects/glimmer-app/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/home/richard/projects/glimmer-app/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/home/richard/projects/glimmer-app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/home/richard/projects/glimmer-app/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/richard/projects/glimmer-app/node_modules/rsvp/dist/rsvp.js:554:13)
    at /home/richard/projects/glimmer-app/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/home/richard/projects/glimmer-app/node_modules/rsvp/dist/rsvp.js:2414:5)
```

**Comment by rwjblue** [comment]
This is due to changes in ember-build-utilities (which was released a few hours ago). Will need to track down which changes are the culprit and address...

**Comment by batusai513** [comment]
ugh, too bad, I was preparing a presentation about glimmer in my local js meetup tomorrow :(

**Comment by rwjblue** [comment]
`yarn upgrade ember-build-utilities@0.1.1` should unblock you

**Comment by batusai513** [comment]
no, that didn't work.

**Comment by BrianSipple** [comment]
@rwjblue I'm still having the same issues after running the upgrade command.

@batusai513 What did you do that led to things not working... but then working? 😃

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-build-utilities/pull/15, running `yarn upgrade ember-build-utilities` should do the trick.

**Comment by batusai513** [comment]
@BrianSipple removed yarn.lock and node_modules and ran `yarn` again
